--From the table STUDENT perform the following queries:
SELECT * FROM STUDENT
--Part – A:
--1. Display rank of students based on SPI.
SELECT STDID, SNAME, CITY, SPI, BRANCH,
RANK() OVER (ORDER BY SPI DESC) AS R_N
FROM STUDENT
--2. Display dense rank of students based on SPI.
SELECT STDID, SNAME, CITY, SPI, BRANCH,
DENSE_RANK() OVER (ORDER BY SPI DESC) AS R_N
FROM STUDENT
--3. Display sequential number for each student record.
SELECT STDID, SNAME, CITY, SPI, BRANCH,
ROW_NUMBER() OVER (ORDER BY SPI DESC) AS R_N
FROM STUDENT
--4. Display branch-wise rank of students.
SELECT STDID, SNAME, CITY, SPI, BRANCH,
RANK() OVER (PARTITION BY BRANCH ORDER BY SPI DESC) AS R_N
FROM STUDENT
--5. Display branch-wise dense ranking of students.
SELECT STDID, SNAME, CITY, SPI, BRANCH,
DENSE_RANK() OVER (PARTITION BY BRANCH ORDER BY SPI DESC) AS R_N
FROM STUDENT
--6. Display branch-wise sequential numbering of students.
SELECT STDID, SNAME, CITY, SPI, BRANCH,
ROW_NUMBER() OVER (PARTITION BY BRANCH ORDER BY SPI DESC) AS R_N
FROM STUDENT
--7. Display SNAME, Current SPI, Previous SPI and SPI Difference with previous student in ascending order of
--SPI.
SELECT SNAME, SPI,
(LAG(SPI) OVER (ORDER BY SPI ASC))-SPI AS DIFF
FROM STUDENT
--8. Display SNAME, Current SPI, Next SPI and SPI Difference with next student in descending order of SPI.
SELECT SNAME, SPI,
(LEAD(SPI) OVER (ORDER BY SPI ASC))-SPI AS DIFF
FROM STUDENT
--9. Display top 3 students based on SPI.
SELECT * FROM
(SELECT STDID, SNAME, CITY, SPI, BRANCH,
DENSE_RANK() OVER (ORDER BY SPI DESC) AS D_R
FROM STUDENT) DATA
WHERE D_R <= 3
--10. Display top 2 students from each branch.
SELECT * FROM
(SELECT STDID, SNAME, CITY, SPI, BRANCH,
DENSE_RANK() OVER (PARTITION BY BRANCH ORDER BY SPI DESC) AS D_R
FROM STUDENT) DATA
WHERE D_R <= 2


--Part – B:
--11. Display 5th highest SPI.
SELECT * FROM
(SELECT STDID, SNAME, CITY, SPI, BRANCH,
DENSE_RANK() OVER (ORDER BY SPI DESC) AS D_R
FROM STUDENT) DATA
WHERE D_R = 5
--12. Display 6th highest SPI.
SELECT * FROM
(SELECT STDID, SNAME, CITY, SPI, BRANCH,
DENSE_RANK() OVER (ORDER BY SPI DESC) AS D_R
FROM STUDENT) DATA
WHERE D_R = 6
--13. Display students having same ranking.
--14. Display SNAME, Previous SPI, Current SPI and Next SPI based on ascending order of SPI.
SELECT SNAME,
LAG(SPI) OVER (ORDER BY SPI ASC) AS LAG_SPI,
 SPI,
LEAD(SPI) OVER (ORDER BY SPI ASC) AS LAG_SPI
FROM STUDENT
--15. Display topper of each branch.
SELECT * FROM
(SELECT STDID, SNAME, CITY, SPI, BRANCH,
DENSE_RANK() OVER (PARTITION BY BRANCH ORDER BY SPI DESC) AS D_R
FROM STUDENT) DATA
WHERE D_R = 1


--Part – C:
--16. Display students whose SPI is greater than the previous student and less than the next student.
SELECT * FROM
(SELECT SNAME, SPI,
LAG(SPI) OVER(ORDER BY SPI ASC) AS LAG_SPI,
LEAD(SPI) OVER(ORDER BY SPI ASC) AS LEAD_SPI
FROM STUDENT) DATA
WHERE LAG_SPI < SPI AND LEAD_SPI > SPI
--17. Display branch-wise second topper students.
SELECT * FROM
(SELECT STDID, SNAME, CITY, SPI, BRANCH,
DENSE_RANK() OVER (PARTITION BY BRANCH ORDER BY SPI DESC) AS D_R
FROM STUDENT) DATA
WHERE D_R = 2
--18. Display students whose rank and dense rank are different.
SELECT * FROM
(SELECT SNAME, SPI,
RANK() OVER(ORDER BY SPI DESC) AS R, 
DENSE_RANK() OVER(ORDER BY SPI DESC) AS D_R
FROM STUDENT) DATA
WHERE R != D_R
--19. Display consecutive students having same branch ordered by SPI.
SELECT * FROM
(SELECT STDID, SNAME, CITY, SPI, BRANCH,
LEAD(BRANCH) OVER (ORDER BY SPI ASC) AS LEAD_B,
LAG(BRANCH) OVER (ORDER BY SPI ASC) AS LAG_B
FROM STUDENT) DATA
WHERE BRANCH = LEAD_B OR BRANCH = LAG_B
--20. Display students whose SPI difference with previous student is maximum.
SELECT TOP 1 * FROM
(SELECT SNAME, SPI,
ABS(LAG(SPI) OVER(ORDER BY SPI ASC)-SPI) AS DIFF
FROM STUDENT) DATA
ORDER BY DIFF DESC


-------------------------
SELECT * FROM
(SELECT SNAME, SPI,
ABS(LAG(SPI) OVER(ORDER BY SPI ASC)-SPI) AS DIFF
FROM STUDENT) X
WHERE DIFF = (SELECT MAX(DIFF) FROM
(SELECT SNAME, SPI,
ABS(LAG(SPI) OVER(ORDER BY SPI ASC)-SPI) AS DIFF
FROM STUDENT) DATA)



