--From the table STUDENT perform the following queries:
SELECT * FROM STUDENT
--Part – A:
--1. Display all students whose SPI is greater than 8.
WITH SPI_GRATER_8 AS (
     SELECT *  FROM STUDENT
     WHERE SPI > 8
)
SELECT * FROM SPI_GRATER_8
--2. Display average SPI of all students.
WITH AVG_SPI AS(
     SELECT STDID, SNAME, AVG(SPI) AS AVG_SPI FROM STUDENT
     GROUP BY STDID, SNAME
)
SELECT * FROM AVG_SPI
--3. Display total number of students in each branch.
WITH TOTAL_STUDENTS AS(
     SELECT BRANCH, COUNT(STDID) AS TOTAL_STUDENTS FROM STUDENT
     GROUP BY BRANCH
)
SELECT * FROM TOTAL_STUDENTS
--4. Display students who belong to RAJKOT city.
WITH RAJKOT_STUDENTS AS(
     SELECT SNAME AS RAJKOT_STUDENTS FROM STUDENT
     WHERE CITY = 'RAJKOT'
)
SELECT * FROM RAJKOT_STUDENTS
--5. Find branch names that appear more than once.
WITH MUL_BRANCH AS (
     SELECT BRANCH, COUNT(STDID) AS COUNT_BRANCH FROM STUDENT
     GROUP BY BRANCH
)
SELECT BRANCH FROM MUL_BRANCH
WHERE COUNT_BRANCH > 1
--6. Display row number for each student.
WITH ROWNUMBER AS(
     SELECT SNAME,
     ROW_NUMBER() OVER( ORDER BY STDID DESC) AS ROWNUMBER
     FROM STUDENT
)
SELECT * FROM ROWNUMBER
--7. Display top 3 students based on SPI.
WITH TOP_3 AS(
     SELECT STDID, SNAME, CITY, SPI, BRANCH,
     DENSE_RANK() OVER (ORDER BY SPI DESC) AS D_R
     FROM STUDENT
)
SELECT TOP 3 * FROM TOP_3
--8. Display students having maximum SPI.
WITH TOPPER AS(
     SELECT STDID, SNAME, CITY, SPI, BRANCH,
     DENSE_RANK() OVER (ORDER BY SPI DESC) AS D_R
     FROM STUDENT
)
SELECT TOP 1 * FROM TOPPER
--9. Display students having minimum SPI.
WITH TOPPER AS(
     SELECT STDID, SNAME, CITY, SPI, BRANCH,
     DENSE_RANK() OVER (ORDER BY SPI ASC) AS REVERSE_D_R
     FROM STUDENT
)
SELECT TOP 1 * FROM TOPPER
--10. Display branch -wise rank of students.
WITH BRANCH_TOPPER AS(
     SELECT STDID, SNAME, CITY, SPI, BRANCH,
     DENSE_RANK() OVER (PARTITION BY BRANCH ORDER BY SPI DESC) AS D_R
     FROM STUDENT
)
SELECT * FROM BRANCH_TOPPER


--Part – B:
--11. Display students SPI average belonging to Computer branch.
WITH COMPUTER_AVG_SPI AS(
     SELECT BRANCH, AVG(SPI) AS AVG_SPI FROM STUDENT
     WHERE BRANCH = 'COMPUTER'
     GROUP BY BRANCH
)
SELECT * FROM COMPUTER_AVG_SPI
--12. Display students whose SPI is greater than average SPI of his/her branch.
WITH BRANCH_GRATERTHAN_AVG AS(
     SELECT BRANCH, AVG(SPI) AS AVG_SPI FROM STUDENT
     GROUP BY BRANCH
)
SELECT * FROM STUDENT S JOIN BRANCH_GRATERTHAN_AVG B
ON S.BRANCH = B.BRANCH
WHERE S.SPI > B.AVG_SPI
--13. Display branch having more than 2 students.
WITH MUL_BRANCH AS (
     SELECT BRANCH, COUNT(STDID) AS COUNT_BRANCH FROM STUDENT
     GROUP BY BRANCH
)
SELECT BRANCH FROM MUL_BRANCH
WHERE COUNT_BRANCH > 2
--14. Display branches having average SPI between 7 and 9
WITH AVG_SPI_BETWEEN_7_9 AS(
     SELECT BRANCH, AVG(SPI) AS AVG_SPI FROM STUDENT
     GROUP BY BRANCH
)
SELECT * FROM AVG_SPI_BETWEEN_7_9
WHERE AVG_SPI BETWEEN 7 AND 9
--15. Display students whose SPI is lower than overall average SPI.
WITH LOWERTHAN_AVG AS(
     SELECT AVG(SPI) AS AVG_SPI FROM STUDENT
)
SELECT * FROM STUDENT S,LOWERTHAN_AVG L
WHERE S.SPI <= L.AVG_SPI 


--Part – C:
--16. Display branches having exactly one student.
WITH ONE_BRANCH AS (
     SELECT BRANCH, COUNT(STDID) AS COUNT_BRANCH FROM STUDENT
     GROUP BY BRANCH
)
SELECT BRANCH FROM ONE_BRANCH
WHERE COUNT_BRANCH = 1
--17. Display branch having highest average SPI.
WITH ONE_BRANCH AS (
     SELECT BRANCH, AVG(SPI) AS AVG_BRANCH FROM STUDENT
     GROUP BY BRANCH
), 
MAX_BRANCH AS(
     SELECT MAX(AVG_BRANCH) AS MAX_AVG FROM ONE_BRANCH 
)
SELECT B.*
FROM ONE_BRANCH B JOIN MAX_BRANCH M
ON B.AVG_BRANCH = M.MAX_AVG
--18. Display branch having lowest average SPI.
WITH ONE_BRANCH AS (
     SELECT BRANCH, AVG(SPI) AS AVG_BRANCH FROM STUDENT
     GROUP BY BRANCH
), 
MIN_BRANCH AS(
     SELECT MIN(AVG_BRANCH) AS MIN_AVG FROM ONE_BRANCH 
)
SELECT B.*
FROM ONE_BRANCH B JOIN MIN_BRANCH M
ON B.AVG_BRANCH = M.MIN_AVG
--19. Display students whose SPI is lower than branch average SPI.
WITH BRANCH_LOWERTHAN_AVG AS(
     SELECT BRANCH, AVG(SPI) AS AVG_SPI FROM STUDENT
     GROUP BY BRANCH
)
SELECT * FROM STUDENT S JOIN BRANCH_LOWERTHAN_AVG B
ON S.BRANCH = B.BRANCH
WHERE S.SPI < B.AVG_SPI
--20. Display branches having maximum number of students.
WITH ONE_BRANCH AS (
     SELECT BRANCH, COUNT(STDID) AS COUNT_BRANCH FROM STUDENT
     GROUP BY BRANCH
), 
MAX_BRANCH AS(
     SELECT MAX(COUNT_BRANCH) AS MAX_COUNT FROM ONE_BRANCH 
)
SELECT B.*
FROM ONE_BRANCH B JOIN MAX_BRANCH M
ON B.COUNT_BRANCH = M.MAX_COUNT
