--Part – A:
--1. INSERT Procedures: Create stored procedures to insert records into STUDENT tables
--(SP_INSERT_STUDENT)
--STDID SNAME CITY SPI BRANCH
--115 PUSHTI RAJKOT 9.48 COMPUTER
--116 NIKUNJ SURAT 8.80 CHEMICAL
CREATE OR ALTER PROCEDURE SP_INSERT_STUDENT
@STDID INT,@SNAME VARCHAR(50),@CITY VARCHAR(50),
@SPI DECIMAL(4,2),@BRANCH VARCHAR(50)
AS
BEGIN
INSERT INTO STUDENT (STDID,SNAME,CITY,SPI,BRANCH)
VALUES(@STDID,@SNAME,@CITY,@SPI,@BRANCH);
END

EXEC SP_INSERT_STUDENT 115,'PUSHTI','RAJKOT',9.48,'COMPUTER';
EXEC SP_INSERT_STUDENT 116,'NIKUNJ','SURAT',8.80,'CHEMICAL';
SELECT * FROM STUDENT

--2. INSERT Procedures: Create stored procedures to insert records into DEPOSIT tables
--(SP_INSERT_DEPOSIT)
--ACTNO CNAME BNAME AMOUNT ADATE
--118 HEMENT BEDI 16000 05-05-2025
--119 RAVI MAVDI 24000 09-07-2024
CREATE OR ALTER PROCEDURE SP_INSERT_DEPOSIT
@ACTNO INT,@CNAME VARCHAR(50),@BNAME VARCHAR(50),
@AMOUNT DECIMAL(10,2),@ADATE DATE
AS
BEGIN
INSERT INTO DEPOSIT VALUES(@ACTNO,@CNAME,@BNAME,@AMOUNT,@ADATE);
END
EXEC SP_INSERT_DEPOSIT 118,'HEMENT','BEDI',16000,'2025-05-05';
EXEC SP_INSERT_DEPOSIT 119,'RAVI','MAVDI',24000,'2024-07-09';
SELECT * FROM DEPOSIT

--3. UPDATE Procedures: Create stored procedure SP_UPDATE_STUDENT to update Branch in STUDENT
--table. (Update using studentID)
--STDID BRANCH
--115 ELECTRICAL
--116 MECHANICAL
CREATE OR ALTER PROCEDURE SP_UPDATE_STUDENT
@STDID INT,@BRANCH VARCHAR(50)
AS
BEGIN
UPDATE STUDENT SET BRANCH=@BRANCH WHERE STDID=@STDID;
END

EXEC SP_UPDATE_STUDENT 115,'ELECTRICAL';
EXEC SP_UPDATE_STUDENT 116,'MECHANICAL';


--4. DELETE Procedures: Create stored procedure SP_DELETE_STUDENT to delete records from STUDENT
--where Student Name is RAVI.
CREATE OR ALTER PROCEDURE SP_DELETE_STUDENT
@SNAME VARCHAR(102)
AS
BEGIN
DELETE FROM STUDENT 
WHERE SNAME=@SNAME;
END
EXEC SP_DELETE_STUDENT 'RAVI';

--5. SELECT BY PRIMARY KEY: Create stored procedures to select records by primary key
--(SP_SELECT_STUDENT_BY_ID) from Student table. (Display All Columns)
CREATE OR ALTER PROCEDURE SP_SELECT_STUDENT_BY_ID
@STDID INT
AS
BEGIN
SELECT * FROM STUDENT WHERE STDID=@STDID;
END
EXEC SP_SELECT_STUDENT_BY_ID 115;
--6. Create a stored procedure that shows details of the first 5 students ordered by SPI (Highest First).
CREATE OR ALTER PROCEDURE SP_TOP_5_STUDENTS
AS
BEGIN 
SELECT TOP 5 * FROM STUDENT ORDER BY SPI DESC; 
END
EXEC SP_TOP_5_STUDENTS;
--From the table EMPLOYEE perform the following queries:

--Part – B:
--7. Create a stored procedure which displays all employee details.
CREATE OR ALTER PROCEDURE SP_SELECT_ALL_EMPLOYEE 
AS 
BEGIN 
SELECT * FROM EMPLOYEE;
END
EXEC SP_SELECT_ALL_EMPLOYEE;
--8. Create a stored procedure that takes department name as input and returns all the employee in that
--department.
CREATE OR ALTER PROCEDURE SP_EMPLOYEE_BY_DEPARTMENT 
@DEPTNAME VARCHAR(50)
AS 
BEGIN 
SELECT * FROM EMPLOYEE WHERE DEPARTMENT=@DEPTNAME; 
END 
EXEC SP_EMPLOYEE_BY_DEPARTMENT 'COMPUTER';

--Part – C:
--9. Create a stored procedure which displays department-wise maximum, minimum, and average salary of
--employee.
CREATE OR ALTER PROCEDURE SP_DEPARTMENT_SALARY 
AS 
BEGIN
SELECT DEPARTMENT, MAX(SALARY) AS MAX_SALARY, MIN(SALARY) AS MIN_SALARY, AVG(SALARY) AS AVG_SALARY FROM EMPLOYEE GROUP BY DEPARTMENT;
END 
EXEC SP_DEPARTMENT_SALARY;

--10. Create a stored procedure that accepts department name as parameter and returns total salary of their
--department.
 CREATE OR ALTER PROCEDURE SP_TOTAL_DEPARTMENT_SALARY 
 @DEPTNAME VARCHAR(50) 
 AS 
 BEGIN 
 SELECT DEPARTMENT,SUM(SALARY) AS TOTAL_SALARY FROM EMPLOYEE WHERE DEPARTMENT=@DEPTNAME GROUP BY DEPARTMENT; 
 END 
EXEC SP_TOTAL_DEPARTMENT_SALARY 'COMPUTER';